namespace Caylang.Assembler.ParseTree
{
    public enum Instruction
    {
        Halt,
        Noop,
        Return,
        Pop,
        Add,
        Subtract,
        Multiply,
        Divide,
        Modulo,
        LoadConst,
        LoadLocal,
        StoreLocal,
        TestEqual,
        TestNotEqual,
        TestGreaterThan,
        TestLessThan,
        Jump,
        JumpTrue,
        JumpFalse,
        CallFunc,
        CallVirtual,
        NewStruct,
        LoadField,
        StoreField,
        NewArray,
        LoadElement,
        StoreElement
    }
}
